# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'scorbot.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTableWidget,
    QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1526, 872)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(420, -30, 421, 301))
        self.groupBox_2.setFlat(True)
        self.base_slider = QSlider(self.groupBox_2)
        self.base_slider.setObjectName(u"base_slider")
        self.base_slider.setGeometry(QRect(250, 70, 160, 22))
        self.base_slider.setCursor(QCursor(Qt.PointingHandCursor))
        self.base_slider.setMouseTracking(False)
        self.base_slider.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.base_slider.setLayoutDirection(Qt.LeftToRight)
        self.base_slider.setMinimum(-155)
        self.base_slider.setMaximum(155)
        self.base_slider.setOrientation(Qt.Horizontal)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(60, 230, 91, 16))
        self.pitch_slider = QSlider(self.groupBox_2)
        self.pitch_slider.setObjectName(u"pitch_slider")
        self.pitch_slider.setGeometry(QRect(250, 190, 160, 22))
        self.pitch_slider.setMinimum(-40)
        self.pitch_slider.setMaximum(130)
        self.pitch_slider.setValue(0)
        self.pitch_slider.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(70, 70, 71, 16))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 110, 41, 16))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 150, 41, 16))
        self.shoulder_slider = QSlider(self.groupBox_2)
        self.shoulder_slider.setObjectName(u"shoulder_slider")
        self.shoulder_slider.setGeometry(QRect(250, 110, 160, 22))
        self.shoulder_slider.setMinimum(-30)
        self.shoulder_slider.setMaximum(125)
        self.shoulder_slider.setValue(125)
        self.shoulder_slider.setOrientation(Qt.Horizontal)
        self.elbow_slider = QSlider(self.groupBox_2)
        self.elbow_slider.setObjectName(u"elbow_slider")
        self.elbow_slider.setGeometry(QRect(250, 150, 160, 22))
        self.elbow_slider.setMinimum(-130)
        self.elbow_slider.setMaximum(130)
        self.elbow_slider.setOrientation(Qt.Horizontal)
        self.roll_slider = QSlider(self.groupBox_2)
        self.roll_slider.setObjectName(u"roll_slider")
        self.roll_slider.setGeometry(QRect(250, 230, 160, 22))
        self.roll_slider.setMinimum(-180)
        self.roll_slider.setMaximum(180)
        self.roll_slider.setSliderPosition(0)
        self.roll_slider.setOrientation(Qt.Horizontal)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 190, 91, 16))
        self.axisSendBtn = QPushButton(self.groupBox_2)
        self.axisSendBtn.setObjectName(u"axisSendBtn")
        self.axisSendBtn.setGeometry(QRect(160, 260, 93, 28))
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(100, 40, 261, 21))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_23.setFont(font)
        self.base_show = QLabel(self.groupBox_2)
        self.base_show.setObjectName(u"base_show")
        self.base_show.setGeometry(QRect(144, 70, 91, 20))
        self.base_show.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.elbow_show = QLabel(self.groupBox_2)
        self.elbow_show.setObjectName(u"elbow_show")
        self.elbow_show.setGeometry(QRect(144, 150, 91, 20))
        self.elbow_show.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pitch_label = QLabel(self.groupBox_2)
        self.pitch_label.setObjectName(u"pitch_label")
        self.pitch_label.setGeometry(QRect(144, 190, 91, 20))
        self.pitch_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.roll_label = QLabel(self.groupBox_2)
        self.roll_label.setObjectName(u"roll_label")
        self.roll_label.setGeometry(QRect(144, 230, 91, 20))
        self.roll_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.shoulder_show = QLabel(self.groupBox_2)
        self.shoulder_show.setObjectName(u"shoulder_show")
        self.shoulder_show.setGeometry(QRect(140, 110, 91, 20))
        self.shoulder_show.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 211, 111))
        self.groupBox.setFlat(True)
        self.searchButton = QPushButton(self.groupBox)
        self.searchButton.setObjectName(u"searchButton")
        self.searchButton.setGeometry(QRect(110, 10, 93, 31))
        self.searchButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 91, 31))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_6.setFont(font1)
        self.comboBoxCom = QComboBox(self.groupBox)
        self.comboBoxCom.setObjectName(u"comboBoxCom")
        self.comboBoxCom.setGeometry(QRect(10, 50, 191, 31))
        self.comboBoxCom.setFont(font1)
        self.stopButton = QPushButton(self.centralwidget)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(240, 10, 161, 51))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(255, 63, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(170, 0, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.stopButton.setPalette(palette)
        font2 = QFont()
        font2.setPointSize(12)
        self.stopButton.setFont(font2)
        self.stopButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.stopButton.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(530, 270, 311, 271))
        self.groupBox_3.setFlat(True)
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 130, 16, 16))
        self.label_9.setFont(font2)
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(50, 90, 16, 16))
        self.label_8.setFont(font2)
        self.lineEditY = QLineEdit(self.groupBox_3)
        self.lineEditY.setObjectName(u"lineEditY")
        self.lineEditY.setGeometry(QRect(70, 90, 51, 22))
        self.lineEditY.setAlignment(Qt.AlignCenter)
        self.lineEditX = QLineEdit(self.groupBox_3)
        self.lineEditX.setObjectName(u"lineEditX")
        self.lineEditX.setGeometry(QRect(70, 50, 51, 22))
        self.lineEditX.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(50, 50, 16, 16))
        self.label_7.setFont(font2)
        self.lineEditZ = QLineEdit(self.groupBox_3)
        self.lineEditZ.setObjectName(u"lineEditZ")
        self.lineEditZ.setGeometry(QRect(70, 130, 51, 22))
        self.lineEditZ.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 0, 291, 41))
        self.label_10.setFont(font)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.cordsSendBtn = QPushButton(self.groupBox_3)
        self.cordsSendBtn.setObjectName(u"cordsSendBtn")
        self.cordsSendBtn.setGeometry(QRect(110, 240, 93, 28))
        self.pitchSldr = QSlider(self.groupBox_3)
        self.pitchSldr.setObjectName(u"pitchSldr")
        self.pitchSldr.setGeometry(QRect(140, 170, 160, 22))
        self.pitchSldr.setMinimum(-40)
        self.pitchSldr.setMaximum(130)
        self.pitchSldr.setValue(0)
        self.pitchSldr.setOrientation(Qt.Horizontal)
        self.rollSldr = QSlider(self.groupBox_3)
        self.rollSldr.setObjectName(u"rollSldr")
        self.rollSldr.setGeometry(QRect(140, 210, 160, 22))
        self.rollSldr.setMinimum(-180)
        self.rollSldr.setMaximum(180)
        self.rollSldr.setOrientation(Qt.Horizontal)
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 210, 41, 20))
        self.label_24.setFont(font2)
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 170, 51, 20))
        self.label_25.setFont(font2)
        self.lineEditPitch = QLineEdit(self.groupBox_3)
        self.lineEditPitch.setObjectName(u"lineEditPitch")
        self.lineEditPitch.setGeometry(QRect(70, 170, 51, 22))
        self.lineEditPitch.setAlignment(Qt.AlignCenter)
        self.lineEditRoll = QLineEdit(self.groupBox_3)
        self.lineEditRoll.setObjectName(u"lineEditRoll")
        self.lineEditRoll.setGeometry(QRect(70, 210, 51, 22))
        self.lineEditRoll.setAlignment(Qt.AlignCenter)
        self.xSldr = QSlider(self.groupBox_3)
        self.xSldr.setObjectName(u"xSldr")
        self.xSldr.setGeometry(QRect(140, 50, 160, 22))
        self.xSldr.setMinimum(-604)
        self.xSldr.setMaximum(604)
        self.xSldr.setValue(119)
        self.xSldr.setOrientation(Qt.Horizontal)
        self.ySldr = QSlider(self.groupBox_3)
        self.ySldr.setObjectName(u"ySldr")
        self.ySldr.setGeometry(QRect(140, 90, 160, 22))
        self.ySldr.setMinimum(-604)
        self.ySldr.setMaximum(604)
        self.ySldr.setValue(0)
        self.ySldr.setOrientation(Qt.Horizontal)
        self.zSldr = QSlider(self.groupBox_3)
        self.zSldr.setObjectName(u"zSldr")
        self.zSldr.setGeometry(QRect(140, 130, 160, 22))
        self.zSldr.setMinimum(0)
        self.zSldr.setMaximum(929)
        self.zSldr.setValue(397)
        self.zSldr.setOrientation(Qt.Horizontal)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(30, 270, 241, 251))
        self.groupBox_4.setFlat(True)
        self.anglesTbl = QLabel(self.groupBox_4)
        self.anglesTbl.setObjectName(u"anglesTbl")
        self.anglesTbl.setGeometry(QRect(40, 10, 191, 20))
        self.anglesTbl.setFont(font)
        self.anglesTbl.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 90, 61, 20))
        self.label_16.setFont(font2)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 50, 61, 20))
        self.label_19.setFont(font2)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 210, 51, 20))
        self.label_20.setFont(font2)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 170, 61, 20))
        self.label_21.setFont(font2)
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 130, 61, 20))
        self.label_22.setFont(font2)
        self.tableWidget = QTableWidget(self.groupBox_4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(90, 40, 101, 201))
        self.label_T3 = QLabel(self.groupBox_4)
        self.label_T3.setObjectName(u"label_T3")
        self.label_T3.setGeometry(QRect(100, 130, 81, 20))
        self.label_T3.setAlignment(Qt.AlignCenter)
        self.label_T1 = QLabel(self.groupBox_4)
        self.label_T1.setObjectName(u"label_T1")
        self.label_T1.setGeometry(QRect(100, 50, 81, 20))
        self.label_T1.setAlignment(Qt.AlignCenter)
        self.label_T4 = QLabel(self.groupBox_4)
        self.label_T4.setObjectName(u"label_T4")
        self.label_T4.setGeometry(QRect(100, 170, 81, 20))
        self.label_T4.setAlignment(Qt.AlignCenter)
        self.label_T2 = QLabel(self.groupBox_4)
        self.label_T2.setObjectName(u"label_T2")
        self.label_T2.setGeometry(QRect(100, 90, 81, 20))
        self.label_T2.setAlignment(Qt.AlignCenter)
        self.label_T5 = QLabel(self.groupBox_4)
        self.label_T5.setObjectName(u"label_T5")
        self.label_T5.setGeometry(QRect(100, 210, 81, 20))
        self.label_T5.setAlignment(Qt.AlignCenter)
        self.homeButton = QPushButton(self.centralwidget)
        self.homeButton.setObjectName(u"homeButton")
        self.homeButton.setGeometry(QRect(10, 210, 201, 41))
        self.homeButton.setFont(font1)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(270, 270, 261, 251))
        self.groupBox_5.setFlat(True)
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 10, 231, 20))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.groupBox_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(70, 130, 16, 16))
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.groupBox_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(70, 50, 16, 16))
        self.label_14.setFont(font2)
        self.label_15 = QLabel(self.groupBox_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(70, 90, 16, 16))
        self.label_15.setFont(font2)
        self.label_17 = QLabel(self.groupBox_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 170, 51, 20))
        self.label_17.setFont(font2)
        self.label_18 = QLabel(self.groupBox_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(50, 210, 41, 20))
        self.label_18.setFont(font2)
        self.xyzTbl = QTableWidget(self.groupBox_5)
        self.xyzTbl.setObjectName(u"xyzTbl")
        self.xyzTbl.setGeometry(QRect(100, 40, 101, 201))
        self.label_x = QLabel(self.groupBox_5)
        self.label_x.setObjectName(u"label_x")
        self.label_x.setGeometry(QRect(110, 50, 81, 20))
        self.label_x.setAlignment(Qt.AlignCenter)
        self.label_y = QLabel(self.groupBox_5)
        self.label_y.setObjectName(u"label_y")
        self.label_y.setGeometry(QRect(110, 90, 81, 20))
        self.label_y.setAlignment(Qt.AlignCenter)
        self.label_z = QLabel(self.groupBox_5)
        self.label_z.setObjectName(u"label_z")
        self.label_z.setGeometry(QRect(110, 130, 81, 20))
        self.label_z.setAlignment(Qt.AlignCenter)
        self.label_pitch = QLabel(self.groupBox_5)
        self.label_pitch.setObjectName(u"label_pitch")
        self.label_pitch.setGeometry(QRect(110, 170, 81, 20))
        self.label_pitch.setAlignment(Qt.AlignCenter)
        self.label_roll = QLabel(self.groupBox_5)
        self.label_roll.setObjectName(u"label_roll")
        self.label_roll.setGeometry(QRect(110, 210, 81, 20))
        self.label_roll.setAlignment(Qt.AlignCenter)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(850, 10, 241, 511))
        self.groupBox_6.setFlat(True)
        self.BaseupBtn = QPushButton(self.groupBox_6)
        self.BaseupBtn.setObjectName(u"BaseupBtn")
        self.BaseupBtn.setGeometry(QRect(20, 10, 93, 28))
        self.BasedwnBtn = QPushButton(self.groupBox_6)
        self.BasedwnBtn.setObjectName(u"BasedwnBtn")
        self.BasedwnBtn.setGeometry(QRect(130, 10, 93, 28))
        self.ShdrupBtn = QPushButton(self.groupBox_6)
        self.ShdrupBtn.setObjectName(u"ShdrupBtn")
        self.ShdrupBtn.setGeometry(QRect(20, 60, 93, 28))
        self.ShdrdwnBtn = QPushButton(self.groupBox_6)
        self.ShdrdwnBtn.setObjectName(u"ShdrdwnBtn")
        self.ShdrdwnBtn.setGeometry(QRect(130, 60, 93, 28))
        self.ElbowupBtn = QPushButton(self.groupBox_6)
        self.ElbowupBtn.setObjectName(u"ElbowupBtn")
        self.ElbowupBtn.setGeometry(QRect(20, 110, 93, 28))
        self.ElbowdwnBtn = QPushButton(self.groupBox_6)
        self.ElbowdwnBtn.setObjectName(u"ElbowdwnBtn")
        self.ElbowdwnBtn.setGeometry(QRect(130, 110, 93, 28))
        self.PitchupBtn = QPushButton(self.groupBox_6)
        self.PitchupBtn.setObjectName(u"PitchupBtn")
        self.PitchupBtn.setGeometry(QRect(20, 160, 93, 28))
        self.PitchdwnBtn = QPushButton(self.groupBox_6)
        self.PitchdwnBtn.setObjectName(u"PitchdwnBtn")
        self.PitchdwnBtn.setGeometry(QRect(130, 160, 93, 28))
        self.RollupBtn = QPushButton(self.groupBox_6)
        self.RollupBtn.setObjectName(u"RollupBtn")
        self.RollupBtn.setGeometry(QRect(20, 210, 93, 28))
        self.RolldwnBtn = QPushButton(self.groupBox_6)
        self.RolldwnBtn.setObjectName(u"RolldwnBtn")
        self.RolldwnBtn.setGeometry(QRect(130, 210, 93, 28))
        self.XdwnBtn = QPushButton(self.groupBox_6)
        self.XdwnBtn.setObjectName(u"XdwnBtn")
        self.XdwnBtn.setGeometry(QRect(130, 330, 93, 28))
        self.XupBtn = QPushButton(self.groupBox_6)
        self.XupBtn.setObjectName(u"XupBtn")
        self.XupBtn.setGeometry(QRect(20, 330, 93, 28))
        self.YdwnBtn = QPushButton(self.groupBox_6)
        self.YdwnBtn.setObjectName(u"YdwnBtn")
        self.YdwnBtn.setGeometry(QRect(130, 380, 93, 28))
        self.YupBtn = QPushButton(self.groupBox_6)
        self.YupBtn.setObjectName(u"YupBtn")
        self.YupBtn.setGeometry(QRect(20, 380, 93, 28))
        self.ZdwnBtn = QPushButton(self.groupBox_6)
        self.ZdwnBtn.setObjectName(u"ZdwnBtn")
        self.ZdwnBtn.setGeometry(QRect(130, 430, 93, 28))
        self.GrCloseBtn = QPushButton(self.groupBox_6)
        self.GrCloseBtn.setObjectName(u"GrCloseBtn")
        self.GrCloseBtn.setGeometry(QRect(12, 257, 101, 31))
        self.GrOpenBtn = QPushButton(self.groupBox_6)
        self.GrOpenBtn.setObjectName(u"GrOpenBtn")
        self.GrOpenBtn.setGeometry(QRect(130, 257, 101, 31))
        self.ZupBtn = QPushButton(self.groupBox_6)
        self.ZupBtn.setObjectName(u"ZupBtn")
        self.ZupBtn.setGeometry(QRect(20, 430, 93, 28))
        self.Orientup_Btn = QPushButton(self.groupBox_6)
        self.Orientup_Btn.setObjectName(u"Orientup_Btn")
        self.Orientup_Btn.setGeometry(QRect(20, 480, 93, 28))
        self.Orientdown_Btn = QPushButton(self.groupBox_6)
        self.Orientdown_Btn.setObjectName(u"Orientdown_Btn")
        self.Orientdown_Btn.setGeometry(QRect(130, 480, 93, 28))
        self.addPosButton = QPushButton(self.centralwidget)
        self.addPosButton.setObjectName(u"addPosButton")
        self.addPosButton.setGeometry(QRect(610, 780, 201, 41))
        self.addPosButton.setFont(font1)
        self.plainTextEditLog = QPlainTextEdit(self.centralwidget)
        self.plainTextEditLog.setObjectName(u"plainTextEditLog")
        self.plainTextEditLog.setGeometry(QRect(10, 550, 551, 271))
        self.plainTextEditLog.setFont(font1)
        self.plainTextEditLog.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.plainTextEditLog.setReadOnly(True)
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(730, 520, 251, 41))
        self.label_26.setFont(font)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 520, 251, 41))
        self.label_27.setFont(font)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.pos_widget = QListWidget(self.centralwidget)
        self.pos_widget.setObjectName(u"pos_widget")
        self.pos_widget.setGeometry(QRect(580, 550, 491, 221))
        self.pos_widget.setFont(font2)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(350, 110, 91, 31))
        self.label_11.setFont(font2)
        self.speed_comboBox = QComboBox(self.centralwidget)
        self.speed_comboBox.setObjectName(u"speed_comboBox")
        self.speed_comboBox.setGeometry(QRect(340, 150, 101, 31))
        self.speed_comboBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.speed_comboBox.setInsertPolicy(QComboBox.InsertAtBottom)
        self.speed_lineEdit = QLineEdit(self.centralwidget)
        self.speed_lineEdit.setObjectName(u"speed_lineEdit")
        self.speed_lineEdit.setGeometry(QRect(340, 190, 101, 31))
        self.speed_lineEdit.setFont(font1)
        self.speed_lineEdit.setAlignment(Qt.AlignCenter)
        self.com_widget = QListWidget(self.centralwidget)
        self.com_widget.setObjectName(u"com_widget")
        self.com_widget.setGeometry(QRect(1100, 10, 391, 541))
        self.com_widget.setFont(font2)
        self.com_edit = QTextEdit(self.centralwidget)
        self.com_edit.setObjectName(u"com_edit")
        self.com_edit.setGeometry(QRect(1100, 560, 391, 51))
        font3 = QFont()
        font3.setPointSize(16)
        self.com_edit.setFont(font3)
        self.add_comBtn = QPushButton(self.centralwidget)
        self.add_comBtn.setObjectName(u"add_comBtn")
        self.add_comBtn.setGeometry(QRect(1080, 630, 191, 51))
        self.add_comBtn.setFont(font1)
        self.del_comBtn = QPushButton(self.centralwidget)
        self.del_comBtn.setObjectName(u"del_comBtn")
        self.del_comBtn.setGeometry(QRect(1080, 700, 191, 51))
        self.del_comBtn.setFont(font1)
        self.exec_Btn = QPushButton(self.centralwidget)
        self.exec_Btn.setObjectName(u"exec_Btn")
        self.exec_Btn.setGeometry(QRect(1350, 630, 141, 51))
        self.exec_Btn.setFont(font2)
        self.save_Btn = QPushButton(self.centralwidget)
        self.save_Btn.setObjectName(u"save_Btn")
        self.save_Btn.setGeometry(QRect(1350, 700, 141, 51))
        self.save_Btn.setFont(font2)
        self.Load_coms_button = QPushButton(self.centralwidget)
        self.Load_coms_button.setObjectName(u"Load_coms_button")
        self.Load_coms_button.setGeometry(QRect(1290, 780, 201, 41))
        self.Load_coms_button.setFont(font1)
        self.delPosButton = QPushButton(self.centralwidget)
        self.delPosButton.setObjectName(u"delPosButton")
        self.delPosButton.setGeometry(QRect(840, 780, 201, 41))
        self.delPosButton.setFont(font1)
        self.Load_pos_button = QPushButton(self.centralwidget)
        self.Load_pos_button.setObjectName(u"Load_pos_button")
        self.Load_pos_button.setGeometry(QRect(1070, 780, 201, 41))
        self.Load_pos_button.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1526, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Scorbot-ER3", None))
        self.groupBox_2.setTitle("")
#if QT_CONFIG(whatsthis)
        self.base_slider.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u044f\u0441\u0442\u044c\u0435 Roll", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u043d\u043e\u0432\u0430\u043d\u0438\u0435", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043b\u0435\u0447\u043e", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u041b\u043e\u043a\u043e\u0442\u044c", None))
#if QT_CONFIG(tooltip)
        self.roll_slider.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u044f\u0441\u0442\u044c\u0435 Pitch", None))
        self.axisSendBtn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043e\u0441\u0435\u0439", None))
        self.base_show.setText("")
        self.elbow_show.setText("")
        self.pitch_label.setText("")
        self.roll_label.setText("")
        self.shoulder_show.setText("")
        self.groupBox.setTitle("")
        self.searchButton.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0438\u0441\u043a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"COM  \u043f\u043e\u0440\u0442", None))
        self.stopButton.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0422\u041e\u041f", None))
        self.groupBox_3.setTitle("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.lineEditX.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0432\u043e\u0434 \u043a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442 \u0438 \u043e\u0440\u0438\u0435\u043d\u0442\u0430\u0446\u0438\u0438", None))
        self.cordsSendBtn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.groupBox_4.setTitle("")
        self.anglesTbl.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u043e\u0441\u0435\u0439", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u044c 2", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u044c 1", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u044c 3", None))
        self.label_T3.setText("")
        self.label_T1.setText("")
        self.label_T4.setText("")
        self.label_T2.setText("")
        self.label_T5.setText("")
        self.homeButton.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u043c\u0430\u0448\u043d\u0435\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435", None))
        self.groupBox_5.setTitle("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043e\u0440\u0434\u0438\u043d\u0430\u0442\u044b \u0437\u0430\u0445\u0432\u0430\u0442\u0430 XYZ", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_x.setText("")
        self.label_y.setText("")
        self.label_z.setText("")
        self.label_pitch.setText("")
        self.label_roll.setText("")
        self.groupBox_6.setTitle("")
        self.BaseupBtn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u043d\u043e\u0432\u0430\u043d\u0438\u0435 +", None))
        self.BasedwnBtn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u043d\u043e\u0432\u0430\u043d\u0438\u0435 -", None))
        self.ShdrupBtn.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043b\u0435\u0447\u043e +", None))
        self.ShdrdwnBtn.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043b\u0435\u0447\u043e -", None))
        self.ElbowupBtn.setText(QCoreApplication.translate("MainWindow", u"\u041b\u043e\u043a\u043e\u0442\u044c +", None))
        self.ElbowdwnBtn.setText(QCoreApplication.translate("MainWindow", u"\u041b\u043e\u043a\u043e\u0442\u044c -", None))
        self.PitchupBtn.setText(QCoreApplication.translate("MainWindow", u"Pitch +", None))
        self.PitchdwnBtn.setText(QCoreApplication.translate("MainWindow", u"Pitch -", None))
        self.RollupBtn.setText(QCoreApplication.translate("MainWindow", u"Roll +", None))
        self.RolldwnBtn.setText(QCoreApplication.translate("MainWindow", u"Roll -", None))
        self.XdwnBtn.setText(QCoreApplication.translate("MainWindow", u"X-", None))
        self.XupBtn.setText(QCoreApplication.translate("MainWindow", u"X+", None))
        self.YdwnBtn.setText(QCoreApplication.translate("MainWindow", u"Y-", None))
        self.YupBtn.setText(QCoreApplication.translate("MainWindow", u"Y+", None))
        self.ZdwnBtn.setText(QCoreApplication.translate("MainWindow", u"Z-", None))
        self.GrCloseBtn.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u0437\u0430\u0445\u0432\u0430\u0442", None))
        self.GrOpenBtn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0437\u0430\u0445\u0432\u0430\u0442", None))
        self.ZupBtn.setText(QCoreApplication.translate("MainWindow", u"Z+", None))
        self.Orientup_Btn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0440\u0438\u0435\u043d\u0442\u0430\u0446\u0438\u044f +", None))
        self.Orientdown_Btn.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0440\u0438\u0435\u043d\u0442\u0430\u0446\u0438\u044f -", None))
        self.addPosButton.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043f\u043e\u0437\u0438\u0446\u0438\u044e", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u0437\u0438\u0446\u0438\u0439", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043d\u0441\u043e\u043b\u044c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c", None))
        self.speed_lineEdit.setText("")
        self.com_edit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.add_comBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
        self.del_comBtn.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
        self.exec_Btn.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.save_Btn.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.Load_coms_button.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u044b", None))
        self.delPosButton.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u043e\u0437\u0438\u0446\u0438\u044e", None))
        self.Load_pos_button.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u043f\u043e\u0437\u0438\u0446\u0438\u0438", None))
    # retranslateUi

